SONIC-DEV/sonic-buildimage

- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/cputemputil.py
- Update platformutil name from platformutil_v1.1.py to platformutil.py
- Add missing code format update on cputemputil for phalanx device
> Update platformutil name and plugin code format.

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- Add firmware management util
- Add CPLD online upgrade tool (ispvm)
> [platform-device/alibaba] - Add cpld upgrade tool and firmware management util.

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sensorutil.py
> 201807 cel

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/sfputil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/sfputil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sfputil.py
- Add API for control port TX signal
- Add BMC utility API
> [platform-device/alibaba] - Add Alibaba device plugin.

- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/th3-as23-128h.config.bcm
> add parameter mdio_output_delay for phalanx

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
> Add timeout for get BMC version!

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
-  Update error handler for bmc watchdog on fwmgrutil
- Update error handler for bmc watchdog to detect error when sending a request to disable/enable bmc watchdog
- Check CPU watchdog status in BMC
> [device/alibaba]: Update error handler for bmc watchdog on fwmgrutil

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
> Fix bmc update failed in V1.2.5

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- Update firmware refresh logger
- Update firmware refresh to record all refresh key
- Add month and date to logger format   
- Invoke `firmware_refresh` api on `fwmgrutil`
- Check refresh log in `/var/log/fw_upgrade.log`
> [device/alibaba]: Update firmware refresh logger

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
> fix BMC update failed from slave

- device/celestica/x86_64-cel_silverstone-r0/plugins/sfputil.py
Update sfputil.py to use OSFP instead QSFP, this change depends on  
[sonic-platform-common#63](https://github.com/Azure/sonic-platform-common/pull/63) to fix xcvr and sfpshow crash!
NOTE: The changes need to rebase onto the master branch to have some fix on sfputilbase.
Update all ports to OSFP instead of QSFP in sfputil plugin.
Run the following commands:
```
show interface presence
show interface transceiver eeprom
show interface transceiver eeprom -d
```
> [plugins/sfputil] Silverstone update sfputil.py to support QSFP-DD

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/sfputil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/sfputil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sfputil.py
- Update tx_disable function in sfputil
- Add presence status detection in tx_disable function for QSFP
- Test tx_disable feature in sfputil
> [device/alibaba]; add presence status detection in sfputil tx_disable function for QSFP

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- Fixed CPLD name param in firmware_refresh API as uppercase
- Reboot BMC after updated
> [device/alibaba]: fix cpld name and bmc reboot issue

- device/celestica/x86_64-cel_silverstone_dp-r0/sonic_platform/chassis.py
[device/celestica] 
- Fixed sysfs path.
- Added dummy event
> Upstream silverstone dp platform api

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/sfputil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/sfputil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sfputil.py
> 201811 cel

- device/alibaba/x86_64-alibaba_as14-40d-cl-r0/bcm56780_a0-generic-40x200.config.yml
> shamu bcm56780 yml config

- .gitmodules
Signed-off-by: Maxwill Ma <mamax@celestica.com>
> modify platform-modules submodule gitHub path

- platform/broadcom/sonic-platform-modules-cel/migaloo/modules/switchboard_fpga.c
- platform/broadcom/sonic-platform-modules-cel/tools/bmcutil/bmc-exec
Signed-off-by: Maxwill Ma <mamax@celestica.com>
>  correct result field name to 'data'

- device/alibaba/x86_64-alibaba_as24-128d-cl-r0/bmc_api_unittest/unittest_config.py
Signed-off-by: Maxwill Ma <mamax@celestica.com>
> correct unittest_config.py syntax error

- device/celestica/x86_64-cel_e1031-r0/platform.json
Add chassis info, such as psu,fan ...
> [device/celestica]: Add platform.json for Seastone-DX010

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
> fix uri error in get_current_bios

- device/celestica/x86_64-cel_seastone_2-r0/plugins/psuutil.py
- platform/broadcom/sonic-platform-modules-cel/debian/rules
- Clean code and fixes bug
- Fix invalid platform_api path on debain build's rule
- Fix lgtm on psuutil
- The package 'target/debs/platform-modules-dx010_1.0_amd64.deb' build should be successful build
> [201811][platform-device/celestica]: various fix

- device/celestica/x86_64-cel_seastone_2-r0/Seastone_2/sai.profile
- device/celestica/x86_64-cel_seastone_2-r0/minigraph.xml
- device/celestica/x86_64-cel_seastone_2-r0/td3-seastone_2-32x100G.config.bcm
> [device/celestica-seastone2]: revert sdk config

- device/celestica/x86_64-cel_seastone_2-r0/Seastone_2/sai.profile
- device/celestica/x86_64-cel_seastone_2-r0/minigraph.xml
- device/celestica/x86_64-cel_seastone_2-r0/plugins/sfputil.py
- device/celestica/x86_64-cel_seastone_2-r0/td3-seastone_2-32x100G.config.bcm
- Update device plugins and sdk config
- [device/celestica-seastone2]: revert sdk config
- [device/celestica-seastone2]: add get_transceiver_change_event api
- xcvrd service
- bcmcmd ps
> [201811][device/celestica]: Update device plugins and sdk config
