- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/cputemputil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/eeprom.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/optictemputil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sensorutil.py
- files/build_templates/sonic_debian_extension.j2
- files/image_config/rsyslog/rsyslog.conf.j2
**New Features:**
*  Phalanx platform base on broadcom platform.
*  Baseboard CPLD driver for Phalanx platform.
*  Switchboard FPGA driver for Phalanx platform.
*  PSU utility for monitoring psu status and information.
*  SFP utility for monitoring sfp status and information.
*  TLV-EEPROM utility for monitoring TLV-EEPROM information.
*  Sensor utility for monitoring sensors status and sensor information.
*  Fan utility for monitoring fan status and fan information.
*  BMC service for send cpu temperature and optic temperature to BMC.
*  Remote syslog service for access BMC syslog.
**Bug Fixed:**
*  Kernel build fail issue.
*  eth0 doesn't exist issue. 
**Known Issues:**
*  sfputil does not support low power mode setting.
> Update Phalanx platform and device plugin.

- files/build_templates/sonic_debian_extension.j2
- Update sync_bmc function to use parallel polling
- Add read_optic_temp.py tool for read all optic modules temperature (file located in /usr/local/etc)
- Remove udev rule revise code.(eth0 issue is cause by eth mac address)
> Upgrade sync bmc service performance and remove unuse code

- .gitmodules
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sensorutil.py
- src/sonic-config-engine/minigraph.py
- src/thrift/Makefile
- Fixed sfp diagnostic monitoring
- Fixed invalid number of power supply unit
- Update libshrift package source.
- Update minigraph parser to avoid exception.
- Fixed invalid power unit on sensor monitoring plugin
- Add fan CPLD sysfs
- Add iMC SMBus for dimm SPD and TSoD access.
> Update Ali platform and device plugin and bug fixes

- .gitmodules
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/cputemputil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/sfputil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/cputemputil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/sfputil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sfputil.py
- Revert sonic-platform-common submodule to use community repository
- Update sfputil to fixed sfp dom issue
- Update device plugins so support platformutil version 1.1
- Update install script to disable sync_bmc.timer by default.
- Update eth0.4088 vlan to support ipv4.
Signed-off-by: Wirut Getbamrung wgetbumr@celestica.com
> Update device plugins and bug fixes

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/psuutil.py
- src/sonic-device-data/tests/permitted_list
- Update device plugins to support null fru data.
- Update device config permitted list to allow specific bcm config.
Signed-off-by: Wirut Getbamrung wgetbumr@celestica.com
> Fix device plugin bug and allow bcm config

- build_debian.sh
- files/image_config/rsyslog/rsyslog.conf.j2
- Remove i2c devices overlap bmc
- Disable imc bus create for 2nd channel.
- Update rsyslog UDPServerAddress
- Add dmidecode tool
> Update Ali platform module driver and bug fixes.

- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/AS23-128H/port_config.ini
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/th3-as23-128h.config.bcm
> modify SDK config for Phalanx

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fanutil.py
- Fix abnormal value return from i2c bus.
- Update sync_bmc service to skip absence module.
- Remove ipv6 on eth0.4088 vlan
- Update fan name for platformutil
> Update Ali platform module driver and fan plugin

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sensorutil.py
- Update sensor naming format in sensorutil.
- Remove IPV6 from eth0.4088 vlan
- Update sync_bmc script to skip absent port.
> [device/alibaba] - Update  sensor naming format in sensorutil.

- platform/broadcom/sai.mk
- Broadcom SAI 3.3 GA 20190118.
- With warm reboot support.
Signed-off-by: Ying Xie <ying.xie@microsoft.com>
> [Broadcom SAI] Upgrade Broadcom SAI to 3.3.4.3-1 (#2472)

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sensorutil.py
- Update phalanx sensor name follow DVT spec.
- Update psuutil to support non-FRU and FRU EEPROM formats.
- Update fwmgrutil to fix invalid data for pcie version
> [device/alibaba] - Update device plugins.

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sensorutil.py
- Update device plugin to support new platformutil
- Update platformutil file
> [device/alibaba] - Update device plugin to support new platformutil

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sensorutil.py
> 201807 cel

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sensorutil.py
- platform/broadcom/sonic-platform-modules-cel/debian/rules
- platform/broadcom/sonic-platform-modules-cel/tools/fpga_prog/fpga_prog.c
- platform/broadcom/sonic-platform-modules-cel/tools/platformutil.py
- Add fpga upgrade tool
- Update plugins to latest version
> [device/alibaba] - Update plugins to latest version

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- Fix switchboard driver auto probe fail bug.
- Update BMC Upgrade function
> [device/alibaba] - Update BMC Upgrade function

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sensorutil.py
- Fix invalid fan cpld monitoring format
- Update platform utility to version 1.2
- Update sensorutil to support INLET_TEMP format
> [device/alibaba] - Update sensor monitoring format.

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/sfputil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/sfputil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sfputil.py
- Update platform utility to version 1.2
- Add api for control port tx signal
- Fix invalid fan cpld monitoring format
- Update sensorutil to support INLET_TEMP format
- Update missing platform module utility and platform configuration 
- Fix platform module init script not load in 201811 branch.
- Revert unintentional change on read_optic_temp.py and sync_bmc.py
> [device/alibaba] - Update device plugins and platform module configuration

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- Fishbone/Phalanx rescan FPGA PCI device after upgrade.
- Update firmware upgrade utility
- Update missing config on bios upgrade function
- Add function to get cpld upgrade information
> [device/alibab] - Update firmware management function.

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- Update cpld upgrade method to support refresh cpld image path
- Update api to get latest upgrade firmware to support BMC and BIOS upgrade log
- Fix invalid line card key for cpld upgrade api
> [device/alibaba] - Update fwmgrutil 

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- Fix an error on fan cpld version monitoring
- Update bios upgrade method to avoid the reboot issue
- Add more switch cpld upgrade type
> [device/alibaba] - Update fwmgrutil to fixes bug

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/optictemputil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/optictemputil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/optictemputil.py
1. Fix the sync_bmc optical module temperature read i2c conflict.
2. Fix the "FPGA device not found!" alert message. 
1. By using optoe's sysfs eeprom instead of reading i2c device from i2ctool. This eliminates the conflict when i2ctool force access EEPROM device when other application, like sfputil, is accessing it. 
2. Remove the faulty condition check in the switchboard_fpga kernel module.  
Now the driver behavior will only be probed(by kernel) when the compatible PCIe device found on the system. Then the platform device/driver initiates the sysfs structure according to the success probe result. If the FPGA device not found on the system, the driver still loaded but no platform device created.
1. When start sync_bmc service …
> Update platform/device to fix bugs

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/sfputil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/sfputil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sfputil.py
Update tx_disable() method in Fishbones and Phalanx to support QSFP port type.
For QSFP port type, use control function address 86, page A0h to set TX_DISABLE signals.
FOr SFP port type, use the TX_DISBLE hardware pin control.
Create a test script to call the SfpUtil.tx_disable() method
Check corresponding sfp_txdisable file(for SFP) / control function byte data(for QSFP) to confirm status change. 
- Fishbone/Phalanx add QSFP tx_dsiable support in sfputil plugins.
> [sfputil-plugins] add tx_disable support for QSFP on fishbone/phalanx

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- Add rsyslog configuration file
- Update get_last_firmware_upgrade api to support multiple upgrade
Signed-off-by: Wirut Getbamrung wgetbumr@celestica.com
> [platform-cel/device-ali] : Add rsyslog configuration and update fwmgrutil

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/psuutil.py
Update Airflow detection format
> [device/alibaba] - Update Airflow detection format

- platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-seastone2.init
- platform/broadcom/sonic-platform-modules-cel/seastone2/cfg/seastone2-modules.conf
Probe ipmi device when kernel boot.
Add the ipmi_devintf and ipmi_si module in module auto probe list.
When system boot up check for `/dev/ipmi0`.
*Probe for ipmi device when OS boot.
> [platform/celestica] Seastone2 probe ipmi dev when os boot

- device/celestica/x86_64-cel_seastone_2-r0/plugins/eeprom.py
- device/celestica/x86_64-cel_seastone_2-r0/plugins/psuutil.py
- device/celestica/x86_64-cel_seastone_2-r0/plugins/sfputil.py
Implement python plugins sfputil, eeprom, and psuutil for seastone2 device.
Implement the eeprom.py to access TLV info.
Implement the sfputil.py to access the SFP info from switchboard driver.
Implement the  psuutil.py to access PSU status via ipmitool.
Run the test case related to sfputil/psuutil/decode-syseeprom described in this:
https://github.com/Azure/SONiC/wiki/Porting-Guide
* Add seastone2 device plugins.
> [device/plugins] Celestica seastone2 add python plugins

- platform/broadcom/sonic-platform-modules-cel/seastone2/modules/switchboard_fpga.c
1. Removed unused I2C bus adapter.
2. Enhance I2C transfer.
3. Codes cleanup.
Update switchboard kernel module to remove unused I2C adapter and sysfs.
Do the regression test on I2C adapter read/write/scan.
*Seastone2 switchboard kernel module enhancement.
> [platform/celestica] Seastone2 switchboard enchantment

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- Update firmware management API to support new firmware upgrade flow
- Modify BMC upgrade type "pingpong" to support BMC upgrade alternative policy 
- Add firmware_program API for FPGA/CPLD version upgrade
- Add firmware_refresh API to support FPGA/CPLD version upgrade
- Add get_running_bmc API for getting a booting flash type of running BMC
- Add set_bmc_boot_flash API for set booting flash of BMC
- Add reboot_bmc API for reboot BMC
- Add get_current_bios API for getting booting bios image type of current running host OS
- Import platform-specific `FwMgrUtil` class and add input to test all functions
> [device/alibaba]: update firmware management API

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- Update firmware_refresh API to support multiple refresh image
- Add support for a list of refresh image on fw_extra key 
- Call firmware_refresh in this following format.
`firmware_refresh(None, ["FAN_CPLD", "SW_CPLD", "BASE_CPLD"], "/tmp/fw/fan_refresh.vme:none:/tmp/fw/base_refresh.vme")`
> [device/alibaba]: Update firmware_refresh API to support multiple refresh image

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
> 201811 cel

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- Update BMC watchdog service to avoid trash Syslog
- Remove BMC watchdog handler on fwmgrutil
- Add missing BMC watchdog service on Phalanx platform
- Remove `bmc_wdt.timer` 
- Update `bmc_wdt.service` to send request to BMC every 20 sec 
- Update `bmc_wdt.sh`  to hide the log
- Remove BMC watchdog handler on fwmgrutil (BMC Restful already supported concurrent request)
- Install BMC watchdog service files to Phalanx platform
- Check BMC watchdog service status on Phalanx via this following command
`systemctl status bmc_wdt.service`
> [device/alibaba]: Update BMC watchdog handler

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- Update firmware_program api to install cpld on cpu side
- Use ispvm tool to install CPLD
- Using API firmware_program nad firmware_refresh
> [device/alibaba]: Update firmware_program api to install cpld on cpu side

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- Update FPGA/CPLD upgrade logger
- Add FPGA/CPLD upgrade logger for `firmware_program` API
- Update get_last_upgrade_result to get data from `firmware_program` API logger
- Upgrade FPGA/CPLD via  firmware_program API
- Check the log file` /var/log/fw_upgrade.log`
> [device/alibaba]: Update FPGA/CPLD upgrade logger

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- Add BMC/BIOS upgrade logger and fix conflict logger bug
- Remove old  BMC/BIOS upgrade logger
- Add BMC/BIOS upgrade logger as same as CPLD/FPGA upgrade logger
- Upgrade BMC/BIOS via `fwmgrutil`
- Check upgrade log in `/var/log/fw_upgrade.log`
> [device/alibaba]: Add BMC/BIOS upgrade logger and fix bug

- device/celestica/x86_64-cel_silverstone-r0/Silverstone-128x100/port_config.ini
Fix the incorrect port index mapping in port_config.ini file.
This bug cause sfputil to return invalid output.
Update the index column of 128x100G config file follows front panel port index.
Run the following command and verify all port can be reset.
```
for i in {0..127..1}; do sudo sfputil reset Ethernet$i ; done 
```
Please see the output in the seperates test log(Shred drive)
- fix Silverstone 128x100G incorrect port mapping.
> [device/celestica] Fix incorrect port index in 128x100G config file.

- files/image_config/logrotate/logrotate.d/rsyslog
- Modify swss logrotate config files
- Modify files/image_config/logrotate/logrotate.d/rsyslog config
- Check num of log files and log file size 
- [swss_logrotate.log](https://github.com/SONIC-DEV/sonic-buildimage/files/3944186/swss_logrotate.log)
> [files/image_config]: update logrotate config for swss

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/sfputil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/sfputil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sfputil.py
- Add reset_all function to sfputil
- Add
reset_all function to sfputil.py on Ali-Fishbone/Phalanx device
- Excecute : sfputil_test.py ([sfputil_test.zip](https://github.com/SONIC-DEV/sonic-buildimage/files/4196997/sfputil_test.zip)) and verify that value must be **`True`**
- Test log: [sfputil_test.log](https://github.com/SONIC-DEV/sonic-buildimage/files/4197776/sfputil_test.log)
> [device/alibaba]: Add reset_all function to sfputil

- platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-questone2bd.init
- platform/broadcom/sonic-platform-modules-cel/questone2bd/modules/switchboard_fpga.c
Update the switchboard FPGA to fix the known bugs found on fishbone48
Update init script to make the platform start after first SONiC install.
Apply the fix to switchboard FPFA driver.
Add small delay in platform init script after initial PCA9548 i2c devices.
* Install fresh SONIC from ONIE, see if all devices initialize successfully.
* The PSU and EEPROM devices can be probed correctly.
* FSC service is running.
* Improve questone2bd platform driver.
> [platform/broadcom] Update questone2bd switchboard driver

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/eeprom.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/eeprom.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sensorutil.py
- Update platform util follow bmc hal api (Phalanx)
- Update fan/psu/sensor/firmware api function to support HAL BMC API ([restful_api_definition.txt](https://github.com/SONIC-DEV/sonic-buildimage/files/4147682/restful_api_definition.txt))
- Excecute : platformutil1.2.py [platformutil1.2.zip](https://github.com/SONIC-DEV/sonic-buildimage/files/4147694/platformutil1.2.zip)
- [phalanx_platformutil_test.log](https://github.com/SONIC-DEV/sonic-buildimage/files/4147671/phalanx_platformutil_test.log)
> [device/alibaba]: Update platform util follow bmc hal api

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/sensorutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fanutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/psuutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/sensorutil.py
1. https://github.com/SONIC-DEV/sonic-buildimage/pull/144/commits/07fc3cd065a8e8b3d7225b5485a919ae5c8765b5
- Replace fanutil.py/fwmgrutil.py/sensorutil.py/psuutil.py of fishbone32
- Replace fanutil.py/fwmgrutil.py/sensorutil.py/psuutil.py of fishbone48
- Replace fanutil.py/fwmgrutil.py/sensorutil.py/psuutil.py of Phalanx
2. https://github.com/SONIC-DEV/sonic-buildimage/pull/144/commits/9f98f3675b028250cb195f1cdb8f0a310b658634
- Update fwmgrutil to fixed some issue
**- Test log**
- [bmc_autotest_nplugin.log](https://github.com/SONIC-DEV/sonic-buildimage/files/4392260/bmc_autotest_nplugin.log)
- [platformutil_nplugin_test.log](https://github.com/SONIC-DEV/sonic-buildimage/files/4392229/platformutil_nplugin_test.log)
> [device/alibaba]: Replace platform util with Ali common util

- device/celestica/x86_64-cel_questone2bd-r0/sensors.conf
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/__init__.py
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/chassis.py
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/component.py
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/eeprom.py
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/fan.py
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/helper.py
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/platform.py
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/psu.py
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/sfp.py
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/thermal.py
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/watchdog.py
- platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-questone2bd.install
- platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-questone2bd.postinst
- platform/broadcom/sonic-platform-modules-cel/questone2bd/setup.py
- Implement Questone2BD platform API version 1.0 base on [`sonic_platform_base`](https://github.com/Azure/sonic-platform-common/tree/201911/sonic_platform_base) on 201911 branch
- Implement chassis api
- Implement component api
- Implement eeprom api
- Implement fan api
- Implement psu api
- Implement thermal api
- Implement watchdog api
- Implement sfp api
- Add api installer script to `sonic-platform-module-cel`
- Verify function output with real device status 
- Verfify api output on sonic cli interface
- Test log: [questone2bd_sonic_api_test.zip](https://github.com/SONIC-DEV/sonic-buildimage/files/4460784/questone2bd_sonic_api_test.zip)
> [device/celestica]: Implement Questone2BD platform API version 1.0

- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/chassis.py
- Fixing slow response on command `show platform firmware`
- Update questone2bd api initialize method on host and pmon docker
- Run command  `# time show platform firmware` on SONIC response time should not over 10 sec 
- Test log :  [questone2bd_show_firmware_test.log](https://github.com/SONIC-DEV/sonic-buildimage/files/4480046/questone2bd_show_firmware_test.log)
> [device/celestica]: Update questone2bd api initialize method

- platform/broadcom/sonic-platform-modules-cel/tools/fanctrl/fand_v2.c
Fix fan control bug that causes segmentation fault when system P/N is not recognized by it.
Update the following component P/N of F2B airflow models:
1. Product PN(TLV): R1241-F9019-01
2. FANs PN(FRU): R1241-FN019-013JW
3. PSU PN(FRU):  DPS-1100FB
Handle the case when system P/N is not recognized by set fan speed to max and exit the program.
Add error log about unrecognize P/N in the system log. 
Change System P/N in TLV EEPROM to something else like "EMPTY" or remove P/N feild.
Then run `service fanctrl restart` the fand_v2 __MUST__ not crash.
An error about unrecognized system P/N logged in the system log.
Fix questone2db fancontrol app crash
Test log: 
```
root@sonic:/home/admin# ./fand_v2 …
```
> [fanctrl] Fix fanctrl crash when system thermal direction is unknown

- device/celestica/x86_64-cel_silverstone_dp-r0/sonic_platform/__init__.py
- device/celestica/x86_64-cel_silverstone_dp-r0/sonic_platform/chassis.py
- device/celestica/x86_64-cel_silverstone_dp-r0/sonic_platform/component.py
- device/celestica/x86_64-cel_silverstone_dp-r0/sonic_platform/eeprom.py
- device/celestica/x86_64-cel_silverstone_dp-r0/sonic_platform/fan.py
- device/celestica/x86_64-cel_silverstone_dp-r0/sonic_platform/helper.py
- device/celestica/x86_64-cel_silverstone_dp-r0/sonic_platform/platform.py
- device/celestica/x86_64-cel_silverstone_dp-r0/sonic_platform/psu.py
- device/celestica/x86_64-cel_silverstone_dp-r0/sonic_platform/sfp.py
- device/celestica/x86_64-cel_silverstone_dp-r0/sonic_platform/thermal.py
- device/celestica/x86_64-cel_silverstone_dp-r0/sonic_platform/watchdog.py
- platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-silverstone-dp.init
- platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-silverstone-dp.install
- platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-silverstone-dp.postinst
- platform/broadcom/sonic-platform-modules-cel/silverstone-dp/setup.py
- Implement Silverstone-DP platform api follow Azure/SONiC#285. and [sonic_platform_base](https://github.com/Azure/sonic-platform-common/tree/master/sonic_platform_base).
1. Implement Chassis APIs.
2. Implement Component APIs.
3. Implement Fan APIs.
4. Implement Psu APIs.
5. Implement Sfp APIs.
6. Implement Watchdog APIs.
7. Implement Thermal APIs.
- Run test script on sonic host and  pmon docker
- Test script: [test_full.zip](https://github.com/SONIC-DEV/sonic-buildimage/files/4537535/test_full.zip)
- Test Log : [silverstone_dp-api-test.log](https://github.com/SONIC-DEV/sonic-buildimage/files/4537536/silverstone_dp-api-test.log)
**Signed-off-by**: Wirut Getbamrung wgetbumr@celestica.com
> [device/celestica]: Implement Silverstone-DP platform api version 1.0

- files/image_config/updategraph/updategraph
> generate config_db.json when boot firsttime after os installing

- files/image_config/platform/rc.local
- files/image_config/updategraph/updategraph
> 201811 cel dev

- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/chassis.py
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/fan.py
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/helper.py
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/psu.py
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/thermal.py
- Update fan / psu APIs
- Fix invalid temperature warning status ( https://github.com/Azure/sonic-platform-daemons/pull/58 )
- Add psu fan direction detector function
- Update max fan rpm value follow hw spec
- Set return temperature type as `float`
- Run `show platform` command in SONIC 
- [thermalctld_issue_test.log](https://github.com/SONIC-DEV/sonic-buildimage/files/4625953/thermalctld_issue_test.log)
> [device/celestica]: Fix thermalctld issue

- device/alibaba/x86_64-alibaba_as13-32h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as13-48f8h-cl-r0/plugins/fwmgrutil.py
- device/alibaba/x86_64-alibaba_as23-128h-cl-r0/plugins/fwmgrutil.py
> 201811 cel dev for openbmc

- platform/broadcom/sonic-platform-modules-cel/questone2bd/modules/pmbus.h
Fix the DPS1100 not working with [sonic-linux-kernel@32963dab](https://github.com/Azure/sonic-linux-kernel/commit/32963dab6b6ea9f9fbda9b2b49a77574453fb8ef)
Update the platform copy of pmbus.h to same with the patched one from sonic-linux-kernel.
* Build the dps1100 with new pmbus.h and load it to kernel.
* Run `sensors` to see the driver is working.
- Fix DPS100 crash with sonic-linux-kernel@32963dab on questone2bd
**Note**
:warning: If the kernel in your sonic is prior to 32963dab, please don't pick this change.
**Test log** 
[fix-dps1100-on-201911_cel_wb.log](https://github.com/SONIC-DEV/sonic-buildimage/files/4660682/fix-dps1100-on-201911_cel_wb.log)
> [platform/questone2bd] Fix DPS1100 crash after sonic kernel patched VID

- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/thermal.py
Add function to get high/low critical threshold function to platform thermal. 
These are called by thermalctld in the latest Azure/201911 commit.
Implement the get_high_critical_threshold()
Implement the get_high_critical_threshold()
Run the `show platform tepperature` and check output restlt.
- Implement temperature critical value read on sonic_platform
Result:
```
admin@sonic:~$ show platform temperature 
NAME    Temperature    High Threshold    Low Threshold    Critical High Threshold    Critical Low Threshold    Warning Status          Timestamp
------------------------  -------------  ----------------  ---------------  -------------------------  ------------------------  ---------------- …
```
> [sonic_api] Implement function to get critical temperature value

- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/chassis.py
- platform/broadcom/sonic-platform-modules-cel/questone2bd/modules/switchboard_fpga.c
Implement polling method to get port insert/remove event in Celestica/ questone2bd.= platform.
- Add sysfs for each port interrupt status.
- Implement get_change_event() in platform chassis. 
- Run the mock up test on chassis.get_change_event()
- Insert/remove the transceiver and check the syslog.
[test_result.zip](https://github.com/SONIC-DEV/sonic-buildimage/files/4769773/test_result.zip)
- Add XCVR insert/remove event support in questone2bd. 
> [device/platform] Implement xcvr insert/remove event on questone2bd

- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/chassis.py
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/fan.py
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/helper.py
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/psu.py
-  update reboot cause api
-  fix psu fan direction api
> [device/celestica]: update api and fixes bug

- platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-questone2bd.init
- platform/broadcom/sonic-platform-modules-cel/questone2bd/modules/Makefile
- platform/broadcom/sonic-platform-modules-cel/questone2bd/modules/i2c-ocores-polling.c
- platform/broadcom/sonic-platform-modules-cel/questone2bd/modules/i2c-ocores-polling.h
- platform/broadcom/sonic-platform-modules-cel/questone2bd/modules/switchboard_fpga.c
Update the bus driver of FPGA I2C master 6 to support master transfer.
And init MAX11617 12-channel ADC on the platform.
This ADC uses to read the CPU and DIMM voltage values.
- Replace the SMBus adapter driver of Master bus 6 to i2c-ocores driver.
- Initialize the max11617 device when the platform starts.
After booting up the unit the iio device shows on `/sys/bus/iio/devices/iio:device0`
- Support CPU and RAM voltage readings on Questone2BD.
Test Log: [max11617-with-i2c-adapter.log](https://github.com/SONIC-DEV/sonic-buildimage/files/4868915/max11617-with-i2c-adapter.log)
> [platform/questone2bd] Support CPU and RAM voltag monitor via ADC

- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/chassis.py
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/event.py
- device/celestica/x86_64-cel_questone2bd-r0/sonic_platform/fan.py
- Implement polling method to get fan insert/remove event in questone2bd platform api
- Implement polling method to get voltage over threshold event in questone2bd platform api
- Modify get_change_event() in platform chassis. 
- Add event.py to store VoltageEvent, FanEvent and SfpEvent class
- Install voltage driver (https://github.com/SONIC-DEV/sonic-buildimage/pull/197)
- Run test script and set an event: [test_event.zip](https://github.com/SONIC-DEV/sonic-buildimage/files/4918227/test_event.zip)
- Test log: [test_event.log](https://github.com/SONIC-DEV/sonic-buildimage/files/4918230/test_event.log)
> [device/celestica]: Add support for fan/voltage event to questone2bd get_change_event api

- build_debian.sh
> block mcelog configuration

- device/alibaba/x86_64-alibaba_as14-128h-cl-r0/bmc_api_unittest/unittest_config.py
Signed-off-by: Maxwill Ma <mamax@celestica.com>
>  correct syntax error in jaws unittest_config.py

- device/celestica/x86_64-cel_seastone-r0/sonic_platform/sfp.py
- platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-dx010.install
- platform/broadcom/sonic-platform-modules-cel/debian/rules
- platform/broadcom/sonic-platform-modules-cel/services/platform_api/platform_api_mgnt.sh
- Add python3 installer for sonic_platform package
1. Add rule to compile sonic_platform package with python3
2. Add command to install python3 package of sonic_platform
- sonic_platform must installed in this `/usr/local/lib/python3.7/dist-packages/sonic_platform` under sonic host and pmon docker
> [platform/cel-dx010]: Add python3 installer for sonic_platform package

- device/celestica/x86_64-cel_seastone-r0/sonic_platform/chassis.py
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/eeprom.py
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/psu.py
1: add/fix soni_platform/psu.py apis
2: add/fix sonic_platform/chassis.py apis
> Add cel seastone platform apis

- device/celestica/x86_64-cel_seastone-r0/sonic_platform/chassis.py
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/sfp.py
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/thermal.py
**- What I did** 
1. fix some failed cases in sfp module
2. fix some failed cases in thermal module
1. Some API return type and value is not correct, for example, expect list type but return bool type. Fix it by correct the return type.
2. Some API not support, add support to it.
Run the Jenkins to show the new testbed platform test result.
> fix some cel seastone platform api failed cases

- device/celestica/x86_64-cel_seastone-r0/platform.json
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/chassis.py
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/fan.py
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/fan_drawer.py
- platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-dx010.init
- Fixed the failed test case of Seastone-DX010's Fan API
- Update Fan APIs follow latest specification
- Update fan configuration in platform.json
- Add fan_drawer APIs
- Verify platform_tests result from SONiC testbed
> [sonic_platform]: Fixed the failed test case of Seastone-DX010's Fan API.

- device/celestica/x86_64-cel_seastone-r0/sonic_platform/watchdog.py
fix watchdog platform too_big_timeout test case fail issue.
define the too_big_timeout to 0xffffff/1000 seconds in sonic mgmt repo test case.
check the too_big_timeout value in seastone sonic platform watchdog.py. 
If this input time out value > defined too_big_timeout, watchdog.py return -1.
Verify it through pytest sonic platform test case.
> watchdog platform too_big_timeout issue fix

- device/celestica/x86_64-cel_seastone-r0/platform.json
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/chassis.py
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/component.py
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/eeprom.py
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/fan.py
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/fan_drawer.py
- device/celestica/x86_64-cel_seastone-r0/sonic_platform/sfp.py
-  Fix Chassis APIs error
-  Fix SFP APIs error
-  Add STATUS_LED_PATH
-  Update EEROM API
-  Update SFP APIs follow Seastone2
- Runing platform api test on testbed 
> [device/celestica]: Fix error on Chassis and SFP APIs

- platform/broadcom/sonic-platform-modules-cel/debian/rules
- Remove unnecessary rule
- Remove silverstone from sonic package build rule
- The package 'target/debs/platform-modules-dx010_1.0_amd64.deb' build should be successful build
> [platform/cel]: remove unnecessary rule
